<?xml version="1.0" encoding="utf-8"?><Database Name="dotnetfinal" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=dotnetfinal.database.windows.net;Initial Catalog=dotnetfinal;User ID=muliyul;Connect Timeout=60" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="dotnetfinalConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Game" Member="Games">
    <Type Name="Game">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Earnings" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="PlayerId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Player_Game" Member="Player" ThisKey="PlayerId" OtherKey="Id" Type="Player" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Player" Member="Players">
    <Type Name="Player">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Bank" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="Player_Game" Member="Games" ThisKey="Id" OtherKey="PlayerId" Type="Game" />
    </Type>
  </Table>
</Database>